version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyR00t@2024!    # 更强的 root 密码
      MYSQL_DATABASE: myapp_db             # 更改数据库名
      MYSQL_USER: dbadmin                  # 更改用户名
      MYSQL_PASSWORD: DbUs3r@2024!         # 更强的用户密码
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./configs/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always

  postgres:
    image: postgres:latest
    container_name: go-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: go-redis
    command: redis-server --requirepass RedisP@ss2024! --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "RedisP@ss2024!", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  postgres_data:
  redis_data: 