// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *CalcRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CalcRequest[number], err)
}

func (x *CalcRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.A, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CalcRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.B, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CalcResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CalcResponse[number], err)
}

func (x *CalcResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Result, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CalcResponse) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Error, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CalcRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *CalcRequest) fastWriteField1(buf []byte) (offset int) {
	if x.A == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetA())
	return offset
}

func (x *CalcRequest) fastWriteField2(buf []byte) (offset int) {
	if x.B == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetB())
	return offset
}

func (x *CalcResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *CalcResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Result == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetResult())
	return offset
}

func (x *CalcResponse) fastWriteField2(buf []byte) (offset int) {
	if x.Error == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetError())
	return offset
}

func (x *CalcRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *CalcRequest) sizeField1() (n int) {
	if x.A == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetA())
	return n
}

func (x *CalcRequest) sizeField2() (n int) {
	if x.B == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetB())
	return n
}

func (x *CalcResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *CalcResponse) sizeField1() (n int) {
	if x.Result == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetResult())
	return n
}

func (x *CalcResponse) sizeField2() (n int) {
	if x.Error == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetError())
	return n
}

var fieldIDToName_CalcRequest = map[int32]string{
	1: "A",
	2: "B",
}

var fieldIDToName_CalcResponse = map[int32]string{
	1: "Result",
	2: "Error",
}
