server:
  port: 8080
  host: 127.0.0.1
  timeout: 10s

database:
  host: localhost
  port: 3306
  user: root
  password: password
  name: mydatabase

  redis:
    host: localhost
    port: 6379
    password: password
    db: 0
