// Code generated by Kitex v0.12.3. DO NOT EDIT.

package calculator

import (
	"context"
	"errors"
	api "example/examples/kitex_demo/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Add": kitex.NewMethodInfo(
		addHandler,
		newAddArgs,
		newAddResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Subtract": kitex.NewMethodInfo(
		subtractHandler,
		newSubtractArgs,
		newSubtractResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	calculatorServiceInfo                = NewServiceInfo()
	calculatorServiceInfoForClient       = NewServiceInfoForClient()
	calculatorServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return calculatorServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return calculatorServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return calculatorServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Calculator"
	handlerType := (*api.Calculator)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.CalcRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Calculator).Add(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddArgs:
		success, err := handler.(api.Calculator).Add(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddArgs() interface{} {
	return &AddArgs{}
}

func newAddResult() interface{} {
	return &AddResult{}
}

type AddArgs struct {
	Req *api.CalcRequest
}

func (p *AddArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.CalcRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddArgs) Unmarshal(in []byte) error {
	msg := new(api.CalcRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddArgs_Req_DEFAULT *api.CalcRequest

func (p *AddArgs) GetReq() *api.CalcRequest {
	if !p.IsSetReq() {
		return AddArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddResult struct {
	Success *api.CalcResponse
}

var AddResult_Success_DEFAULT *api.CalcResponse

func (p *AddResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.CalcResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddResult) Unmarshal(in []byte) error {
	msg := new(api.CalcResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddResult) GetSuccess() *api.CalcResponse {
	if !p.IsSetSuccess() {
		return AddResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.CalcResponse)
}

func (p *AddResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddResult) GetResult() interface{} {
	return p.Success
}

func subtractHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.CalcRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Calculator).Subtract(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SubtractArgs:
		success, err := handler.(api.Calculator).Subtract(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SubtractResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSubtractArgs() interface{} {
	return &SubtractArgs{}
}

func newSubtractResult() interface{} {
	return &SubtractResult{}
}

type SubtractArgs struct {
	Req *api.CalcRequest
}

func (p *SubtractArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.CalcRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SubtractArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SubtractArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SubtractArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SubtractArgs) Unmarshal(in []byte) error {
	msg := new(api.CalcRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SubtractArgs_Req_DEFAULT *api.CalcRequest

func (p *SubtractArgs) GetReq() *api.CalcRequest {
	if !p.IsSetReq() {
		return SubtractArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SubtractArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SubtractArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SubtractResult struct {
	Success *api.CalcResponse
}

var SubtractResult_Success_DEFAULT *api.CalcResponse

func (p *SubtractResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.CalcResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SubtractResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SubtractResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SubtractResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SubtractResult) Unmarshal(in []byte) error {
	msg := new(api.CalcResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SubtractResult) GetSuccess() *api.CalcResponse {
	if !p.IsSetSuccess() {
		return SubtractResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SubtractResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.CalcResponse)
}

func (p *SubtractResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SubtractResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Add(ctx context.Context, Req *api.CalcRequest) (r *api.CalcResponse, err error) {
	var _args AddArgs
	_args.Req = Req
	var _result AddResult
	if err = p.c.Call(ctx, "Add", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Subtract(ctx context.Context, Req *api.CalcRequest) (r *api.CalcResponse, err error) {
	var _args SubtractArgs
	_args.Req = Req
	var _result SubtractResult
	if err = p.c.Call(ctx, "Subtract", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
